# Generated by Django 4.2.6 on 2024-06-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind Speed')),
                ('percipitation', models.FloatField(blank=True, null=True, verbose_name='Percipitation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapturedWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticky_sack', models.BooleanField(default=False, verbose_name='Sticky Sack')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('weather_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictor.weatherdata')),
            ],
        ),
    ]
