# Generated by Django 4.2.6 on 2024-06-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='percipitation',
            new_name='precipitation',
        ),
    ]
