# Generated by Django 4.2.6 on 2024-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_rename_percipitation_weatherdata_precipitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedweatherdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='capturedweatherdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(blank=True, null=True, verbose_name='Precipitation'),
        ),
    ]
