# Generated by Django 4.2.6 on 2024-06-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_capturedweatherdata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedweatherdata',
            name='weather_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.weatherdata'),
        ),
    ]
