# Generated by Django 4.2.6 on 2024-06-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_capturedweatherdata_weather_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedweatherdata',
            name='weather_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.weatherdata'),
        ),
    ]
